image: buildpack-deps:jessie-scm

before_script:
  - curl -sSL https://get.docker.com/ | sh
  - docker login -u $DOCKER_HUB_USERNAME -p $DOCKER_HUB_PASSWORD -e $DOCKER_HUB_EMAIL

stages:
  - release

bleeding-edge:
  stage: release
  script:
    - docker pull buildpack-deps:jessie-scm
    - docker build --no-cache=true -t chouandy/docker-base:$CI_BUILD_REF_NAME .
    - docker push chouandy/docker-base:$CI_BUILD_REF_NAME
  only:
    - develop

stable-release:
  stage: release
  script:
    - docker build -t chouandy/docker-base:$CI_BUILD_TAG .
    - docker push chouandy/docker-base:$CI_BUILD_TAG
    - docker tag -f chouandy/docker-base:$CI_BUILD_TAG chouandy/docker-base:latest
    - docker push chouandy/docker-base:latest
  only:
    - tags
